defaults:
  - env/frankasim_pickcube_vision@env.train
  - env/frankasim_pickcube_vision@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: 0-3
    # env: 0
    # rollout: 0
    # actor: 1-3

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "franka_sim_ppo_openpi_pi05"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1
  only_eval: false
  val_check_interval: 10
  save_interval: 50


  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: true
  kl_penalty: kl
  group_size: 1
  reward_coef: 1.0

  rollout_epoch: 1
  eval_rollout_epoch: 1
  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level
  update_epoch: 5

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: token-mean

  bootstrap_type: always
  kl_beta: 0.0
  entropy_bonus: 0.005
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  sampling_params:
    do_sample: true
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: EnvGroup

  train:
    obs_format: tensor
    wrap_obs_mode: openpi
    total_num_envs: 24
    group_size: ${algorithm.group_size}
    auto_reset: true
    max_steps_per_rollout_epoch: 100
    max_episode_steps: 100

    use_rel_reward: true
    reward_coef: ${algorithm.reward_coef}
    is_eval: false
    video_cfg:
      save_video: false
      info_on_video: true
      video_base_dir: ${runner.logger.log_path}/video/train

  eval:
    obs_format: tensor
    wrap_obs_mode: openpi
    total_num_envs: 24
    group_size: ${algorithm.group_size}
    auto_reset: true
    ignore_terminations: false
    max_steps_per_rollout_epoch: 100
    max_episode_steps: 100

    use_rel_reward: true
    reward_coef: ${algorithm.reward_coef}
    is_eval: true
    video_cfg:
      save_video: true
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: RolloutGroup
  backend: huggingface
  enable_offload: false
  pipeline_stage_num: 1
  collect_prev_infos: true

  model:
    model_path: "/workspace/RLinf/weight/RLinf-Pi05-SFT"
    precision: ${actor.model.precision}

  enable_torch_compile: false
  enable_cuda_graph: false

actor:
  group_name: ActorGroup
  training_backend: fsdp
  micro_batch_size: 32
  global_batch_size: 1024
  seed: 0
  enable_offload: false

  model:
    model_type: "openpi"
    model_path: "/workspace/RLinf/weight/RLinf-Pi05-SFT"
    is_lora: false
    lora_rank: 32
    action_dim: 4
    add_value_head: true
    num_action_chunks: 1
    num_steps: 4
    openpi:
      # Keep Franka-specific data transforms, but use a PPO recipe close to ManiSkill Pi0.5.
      value_after_vlm: true
      config_name: "pi05_custom"
      pi05: true
      num_images_in_input: 1
      noise_method: "flow_noise"
      noise_params: [0.16, 0.12, 200]
      joint_logprob: true
      # action_chunk: ${actor.model.num_action_chunks}
      # num_steps: ${actor.model.num_steps}
      # train_expert_only: true
      # action_env_dim: ${actor.model.action_dim}
      # add_value_head: ${actor.model.add_value_head}
    policy_setup: widowx_bridge

  optim:
    lr: 7.91e-6
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0
    critic_warmup_steps: 0

  fsdp_config:
    strategy: fsdp
    sharding_strategy: no_shard
    gradient_checkpointing: false
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: false

critic:
  use_critic_model: false
